### ISSUE TITLE
Bug: Plugin raises an error when used with webpack v2

### ISSUE THREAD

**Issue by TheDartCode** [MikaAK/s3-plugin-webpack#102]
# Complete the following or your issue will be deleted (delete me after)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood this plugin's README
- [x] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

Thank you for adhering to this process! This ensures that I can pay attention to issues that are relevant and answer questions faster.

# Issue Details

If filing a bug report, please include **a list of steps** that describe how to
reproduce the bug you are experiencing. Include your config being passed to the `S3Plugin`.

Hello,

since 88d59defec46f042b83f4171f0e202731b3be34f the plugin is not compatible with webpack v2 (and v3 if I am not mistaken).

The breaking change is https://github.com/MikaAK/s3-plugin-webpack/commit/88d59defec46f042b83f4171f0e202731b3be34f#diff-2782aaa7ef352e5c54bd602be4546049L88

and the error raised is
```
TypeError: Cannot read property 'afterEmit' of undefined  
```

Is there any plan to add compatibility?
Maybe I can help as well.

Thanks!

**Comment by MikaAK** [comment]
Use older version pre 1.

**Comment by tquetano-r7** [comment]
FYI this also surfaces for webpack 3.

**Comment by MikaAK** [comment]
The api has changed a fair bit internally between webpack 3-4. IIRC. I can release a seperate version for webpack 3 if you would like that's just the rc re-released under non rc.
