### ISSUE TITLE
Issue with Patch version upgrade of web pack-s3-plugin

### ISSUE THREAD

**Issue by 2dev2** [MikaAK/s3-plugin-webpack#103]
# Complete the following or your issue will be deleted (delete me after)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x ] I have read and understood this plugin's README
- [x ] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [ x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [ x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [ x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x ] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

Thank you for adhering to this process! This ensures that I can pay attention to issues that are relevant and answer questions faster.

# Issue Details

Previously we have used web pack-s3-plugin "^1.0.0-rc.0", and with the new release of 1.0.2-rc.0 we got the error.
yarn version: yarn@1.7.0
node version: v8.9.1
webpack version: 3.8.1

When we are building the Project with web-pack, we are getting compile time error.

[[ Failed to compile.
Cannot read property 'afterEmit' of undefined ]]

Can we give more description about the error.
It should not break the backward compatibility.

**Comment by MikaAK** [comment]
Fallback to v1rc till a release is drafted for webpack 3, latest version won't support webpack 3.
