### ISSUE TITLE
issue with cdnizer

### ISSUE THREAD

**Issue by tuananh** [MikaAK/s3-plugin-webpack#106]
# Complete the following or your issue will be deleted (delete me after)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood this plugin's README
- [x] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

Thank you for adhering to this process! This ensures that I can pay attention to issues that are relevant and answer questions faster.

# Issue Details

If filing a bug report, please include **a list of steps** that describe how to
reproduce the bug you are experiencing. Include your config being passed to the `S3Plugin`.

I'm using this config

```
new S3Plugin({
    include: /.*\.(css|js|svg|png|jpg|map)/,
    s3Options: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
        region: 'ap-southeast-1'
    },
    s3UploadOptions: {
        Bucket: 'mydomain.com'
    },
    cdnizerOptions: {
        defaultCDNBase: '//mydomain.com/build',
        allowRev: false,
        allowMin: false,
        files: ['*{chunk,bundle}*.{css,js}']
    },
    directory: 'build',
    basePath: 'build'
})
```

However, a file named `manifest.json` in `index.html` like this `<link rel="manifest" href="/assets/manifest.json">` still got cdnize and become `<link rel="manifest" href="//mycdn.com/build/assets/manifest.json">`

**Comment by MikaAK** [comment]
Thanks for the report, https://github.com/MikaAK/s3-plugin-webpack/blob/master/src/s3_plugin.js#L175 seems to be the culprit here, where it is overriding files. I'll make a fix

**Comment by tuananh** [comment]
@MikaAK thanks for the quick response. it's indeed the issue. i tried comment that line and it works as expected for me. however im not sure about the impact that it may cause.

**Comment by MikaAK** [comment]
It causes the html files to get cdnized, however I don't think files work like you expect. Files is used to choose which files to run cdnizdr on. You can't exclude specific links using that. Look at `matchers` instead

**Comment by tuananh** [comment]
@MikaAK but if i be more specific with my globs (`files`), i can exclude it right?

**Comment by MikaAK** [comment]
no that's now how `files` work. @tuananh  `files` is only saying which files cnizer is called on. It has nothing to do with which links in those files get converted
