### ISSUE TITLE
Peer dependencies: webpack ^4

### ISSUE THREAD

**Issue by utlime** [MikaAK/s3-plugin-webpack#108]
# Complete the following or your issue will be deleted (delete me after)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood this plugin's README
- [ ] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [ ] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [ ] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

Thank you for adhering to this process! This ensures that I can pay attention to issues that are relevant and answer questions faster.

# Issue Details

Hi, i have question about dependencies.
Can we use this library with webpack v3?
I found that latest releases contain webpack: ^4 in peerDependencies. 

I've checked dist code and i don't see that you use webpack.
Is it possible remove webpack from peerDependencies?

Thank you!

re  #101

**Comment by MikaAK** [comment]
downgrade
