### ISSUE TITLE
double path is added if files are input with / at start

### ISSUE THREAD

**Issue by emilsedgh** [MikaAK/s3-plugin-webpack#112]
# Complete the following or your issue will be deleted (delete me after)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood this plugin's README
- [x] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

# Issue Details

Version 0.9.2 doesn't actually work with cdnizer because it tries to use the pattern `*${name}*` instead of `{/,}*${name}*`.

I patched it in [a personal branch](https://github.com/emilsedgh/s3-plugin-webpack/tree/0.9.3) and called it 0.9.3 but I cannot do a pull request as you don't have a branch based on that version.

Feel free to release a 0.9.3 for people who are still on Webpack 3. This may save some of their time figuring out what's wrong.

**Comment by MikaAK** [comment]
Would you be able to explain the difference between the two?

**Comment by emilsedgh** [comment]
Well webpack is inserting filenames like `/core.<hash>.js` into my html.
Cdnizer wont replace `/core.<hash>.js` with the first pattern.
It works fine with the latter pattern.

**Comment by MikaAK** [comment]
that's a bit odd, by default it should not have a `/`, I've not had a leading `/` since I started with webpack

**Comment by MikaAK** [comment]
Is this still a problem?
