### ISSUE TITLE
ERROR in S3Plugin: NetworkingError: write EPIPE 

### ISSUE THREAD

**Issue by Instrumedley** [MikaAK/s3-plugin-webpack#116]
Hi, I'm not sure why this is happening and if it's an issue or just some networking nonsense by aws, but here it is.
We use  2 test buckets, a staging bucket and our production on aws S3. We have been using webpack to deploy our front-end there since ages with never this problem. We are located in Europe. 
Then now I'm working home-office from my home-country in Brazil and when I try to deploy to any of the test  or production buckets (not staging for whatever reason) I get the following error:

> ERROR in S3Plugin: NetworkingError: write EPIPE

I could not find much info about this.
I'm using MacOS 10.11.6 , webpack-s3-plugin@1.0.0-rc.0 .

Here is the relevant piece of code where I'm using the S3 plugin:

`if (environment.bucket) {
		var s3obj = {
			s3Options: {
				accessKeyId: envJSON.aws.accessKeyId,
				signatureVersion: 'v4',
				secretAccessKey: envJSON.aws.secretAccessKey,
				region: 'eu-central-1'
			},
			s3UploadOptions: {
				Bucket: environment.bucket,
				CacheControl: 'max-age=315360000, no-transform, public'
			}			
		};

		// Only production uses Cloudfront
		if (env.ENVFILE == 'production') {
			s3obj.cloudfrontInvalidateOptions = {
				DistributionId: envJSON.cloudfront.distributionId,
				Items: ["/*"]
			};
		}

		plugins.push(new S3Plugin(s3obj));
	}`

However, I know there's nothing wrong with the code, as my colleague back in Europe is able to deploy just as usual. It only happens to me after I came to South America. Anyone has any clue?

**Comment by MikaAK** [comment]
I'm not sure if this has much to do with the lib so much as your networking. Feel free to comment otherwise
