### ISSUE TITLE
Ability to disable multi-part uploads

### ISSUE THREAD

**Issue by dniccum** [MikaAK/s3-plugin-webpack#117]
# Issue Details

I am currently attempting to use this plugin with a hosting provider that uses a customized instance of S3. I am not sure if this has to do with some infrastructure changes that they have made internally, or an SDK API version change, but nevertheless, the plugin has recently stopped working for me.

During my uploads, and I am getting this error:

```
Bad Request: Multipart upload not supported
```

Which after further discovery, their S3 bucket does not allow multipart uploads. With that said, is there a way that I can force the plugin to not do concurrent, multi-part uploads?

Thanks for your time.

**Comment by MikaAK** [comment]
s3UploadOptions/s3Options are piped directly in aws, if anything you'll find an option there

**Comment by dniccum** [comment]
Already looked, thanks.
