### ISSUE TITLE
AWS CloudFront API deprecation

### ISSUE THREAD

**Issue by rennokki** [MikaAK/s3-plugin-webpack#118]
Don't worry, this might not be a real problem, I just wanted to notify that the CF API will deprecate prior to 2016: https://forums.aws.amazon.com/ann.jspa?annID=6697

I'm not sure if this will impact the app itself, but will look after it, just wanted to notify you about this.

**Comment by MikaAK** [comment]
Thanks for bringing this up, in case it does impact us we should check into it

**Comment by rennokki** [comment]
I hope this won't break the app. The version constraint is updating the AWS SDK to the latest major.

**Comment by MikaAK** [comment]
June 6th is comming up, I'll be weary if anything fails

**Comment by MikaAK** [comment]
Well we passed!
