### ISSUE TITLE
react-scripts@3.0.0 gives "path" argument must be one of type string, Buffer, or URL error

### ISSUE THREAD

**Issue by fracmak** [MikaAK/s3-plugin-webpack#119]
**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood this plugin's README
- [x] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

Thank you for adhering to this process! This ensures that I can pay attention to issues that are relevant and answer questions faster.

# Issue Details

Just tried upgrading to react-scripts@3.0.0 and it appears to break this plugin. Specifically the getAssetFiles() function no longer works properly because the assets object passed in is in a different format. The existsAt property is no longer there. In 3.0.0 the assets object now looks like this
```
static/media/logo.5d5d9eef.svg {"_size":2671}
```

while in 2.1.8 it looks like this
```
static/media/logo.5d5d9eef.svg {"_value": Buffer, "existsAt":".....","emitted":true}
```

**Comment by MikaAK** [comment]
Did you have a solution in mind? It seems like a react-scripts problem since the backwards compatibility with file is broken

**Comment by fracmak** [comment]
I'll dig further, wanted to document what I'd found so far incase anyone had some easy solutions.

**Comment by MikaAK** [comment]
Any further info @fracmak?

**Comment by leagerl1** [comment]
FYI setting `config.output.futureEmitAssets = false` in your webpack config generated from react-scripts 3.x.x will revert the manifest output to the format expected by s3-plugin-webpack and allow it to work

**Comment by MikaAK** [comment]
Looks like this will be the default in webpack 5 so we'll need a fix before then, thanks for investigating @leagerl1
