### ISSUE TITLE
TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by lasantha57** [MikaAK/s3-plugin-webpack#120]
# Complete the following or your issue will be deleted (delete me after)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood this plugin's README
- [x] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

Thank you for adhering to this process! This ensures that I can pay attention to issues that are relevant and answer questions faster.

# Issue Details

Recently I migrated from Webpack build to Angular CLI. However, I am maintaining a custom webpack config to manage the file uploading to s3. Here are my custom webpack configurations for `webpack-s3-plugin`.

```
module.exports = (config) => {

  if (config.mode === 'production') {

    const S3Plugin = require('webpack-s3-plugin');

    config.plugins.push(...[
      new S3Plugin({
        s3Options: {
          accessKeyId: 'xxxxxxxxxx',
          secretAccessKey: 'xxxxxxxxxxxxxxxxx',
          region: 'xxxxxxxx'
        },
        s3UploadOptions: {
          Bucket: 'xxxxxxxxxxxxxxxxx',
          CacheControl: 'public, must-revalidate, proxy-revalidate, max-age=0'
        }
      })
    ]);
  }
  return config;
};

```

Once the build happens I'm getting the following error. However, I can see my build files inside `dist` folder and I can run my app locally without any failure.

```
TypeError: path must be a string or Buffer
    at Object.fs.open (fs.js:636:11)
    at ReadStream.open (fs.js:1996:6)
    at new ReadStream (fs.js:1983:10)
    at Object.fs.createReadStream (fs.js:1931:10)
    at t.exports.uploadFile (/Users/lasantha/HuubHR/huubhr-front-end/node_modules/webpack-s3-plugin/dist/s3_plugin.js:1:6689)
    at t.map.t (/Users/lasantha/HuubHR/huubhr-front-end/node_modules/webpack-s3-plugin/dist/s3_plugin.js:1:6330)
    at Array.map (<anonymous>)
    at transformBasePath.then (/Users/lasantha/HuubHR/huubhr-front-end/node_modules/webpack-s3-plugin/dist/s3_plugin.js:1:6318)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

Here is my npm script: 
`"build": "ng build --progress --prod -c production"`

Here are my package versions.

```
"@angular-builders/custom-webpack": "7.4.3"
"@angular-devkit/build-angular": "0.13.9"
"@angular/cli": "7.3.9"
"@angular/compiler-cli": "7.2.15"
"@angular/compiler": "7.2.15"
"@angular/core": "7.2.15"
"webpack-s3-plugin": "1.0.3"
"typescript": "3.2.4"
```

Other details

```
OS: macOS Hight Sierra 10.13.6
node: 8.12.0
npm: 6.4.1
```

**Comment by MikaAK** [comment]
What other webpack config do you have, never seen a case like this before and library hasn't changed all that much in years

**Comment by lasantha57** [comment]
I don't have any other webpack config. I have been using this library for a long time. However I upgraded the application from angular 6 to 7. Till then I had no issue like this. Still I'm trying to sort out this. thanks

**Comment by MikaAK** [comment]
This sounds like more a specific issue with ng than with the lib since this lib provides standard behaviour. Unfortunately I don't think there's anything that we can do here

**Comment by lasantha57** [comment]
Thanks for the feedback @MikaAK 🙇

**Comment by lasantha57** [comment]
@MikaAK I found that the issue was with the `@angular-devkit/build-angular`. I tried `0.12.4` and now it's working as expected.
The above issue exists for `@angular-devkit/build-angular: 0.13.x`. Thanks

**Comment by mrudult** [comment]
I encountered the same issue when using CRA and `react-scripts 3.0.0+`. Had to downgrade react-scripts to `2.1.8`
