### ISSUE TITLE
The specified distribution does not exist.

### ISSUE THREAD

**Issue by btmdave** [MikaAK/s3-plugin-webpack#122]
Using the `cloudfrontInvalidateOptions` I seem to always get `NoSuchDistribution: The specified distribution does not exist.`.  I've verified the distribution id is correct and it's deploying to the bucket correctly, however it just doesn't seem to recognize the distribution id.  The profile being used has access to everything.   Any ideas what could be causing this?

```
      new S3Plugin({
        s3Options: {
          credentials: new AWS.SharedIniFileCredentials({ profile: 'xxx' })
        },
        s3UploadOptions: {
          Bucket: 'app'
        },
        cloudfrontInvalidateOptions: {
          DistributionId: 'E2L4L4FF5IE35C',
          Items: ['/*']
        }
      })
```

**Comment by MikaAK** [comment]
I'm not sure, it sounds like a config issue though
