### ISSUE TITLE
Help, how to specify relaxed root caching policy?

### ISSUE THREAD

**Issue by Birowsky** [MikaAK/s3-plugin-webpack#123]
How to specify root `example.com` caching policy of an hour, while the rest of the S3 objects would have max age of a year?

**Comment by MikaAK** [comment]
```javascript
s3UploadOptions: {
 CacheControl: (fileName) => fileName === "index.html" ? indexCaching : otherCaching
}
```

**Comment by Birowsky** [comment]
Sorry, I'm a bit confused. Based on [their types here](https://github.com/aws/aws-sdk-js/blob/2212c8f7e2981a43c8ecc272d2b3a7dc7b35e1bd/clients/s3.d.ts#L995), CacheControl accepts only a string. Where does the change you are implying happen?

**Comment by Birowsky** [comment]
Aha, I guess [this is the one](https://github.com/MikaAK/s3-plugin-webpack/blob/2e59cc2ca91b1577bf5a4999c284ca74982ef687/src/s3_plugin.js#L291).

Dude, types are gonna save the world ; ]

**Comment by MikaAK** [comment]
This project is so old now, i made it before typescript was a thing 😮

**Comment by Birowsky** [comment]
![giphy](https://user-images.githubusercontent.com/3199950/60643435-55b5a880-9e33-11e9-910e-3c3726e6cb81.gif)
