### ISSUE TITLE
Problem with directory option

### ISSUE THREAD

**Issue by StefanNiederkofler** [MikaAK/s3-plugin-webpack#124]
- [x] I have read and understood this plugin's README
- [ ] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [ ] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [ ] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

# Issue Details

I have to use the "directory" option, set to "public/build", because i use the CopyWebpackPlugin and so the s3Plugin should Upload the whole directory.
The problem that i have is, that the "directory" option is added to my "basePath".

So if a have this config:
```
basePath: 'build', // This is the name the uploaded directory will be given
directory: 'public/build' // This is the directory you want to upload
```
the folder structure on the s3 looks like this:
`build/public/build/`
I could leave the basePath empty, that would result in this on s3:
`public/build`

I have to get rid of the "public". I use this in a symfony project, and the "public" folder is the project web root.

Any suggestions on how can I solve this?

**Comment by seeliang** [comment]
@StefanNiederkofler have you found a walk-around?
