### ISSUE TITLE
endpoint-url option

### ISSUE THREAD

**Issue by viartemev** [MikaAK/s3-plugin-webpack#126]
# Complete the following or your issue will be deleted (delete me after)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood this plugin's README
- [x] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

Thank you for adhering to this process! This ensures that I can pay attention to issues that are relevant and answer questions faster.

# Issue Details
s3-plugin-webpack version: 1.3.2
OS: MacOS

AWS client has `--endpoint-url` option which is useful for using with others S3 compatible cloud providers. Could you add this option?
The AWS Endpoint documentation: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Endpoint.html

**Comment by MikaAK** [comment]
PR's are welcome but this isn't really a priority since this is intended for s3

**Comment by pscheit** [comment]
for e.g. minio go like this:

```
                s3Options: {
                  accessKeyId: process.env.AWS_ACCESS_KEY_ID,
                  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
                  endpoint: 'https://my-minio-server',
                  s3ForcePathStyle: true,
                  signatureVersion: 'v4',
                  logger: console
                },
```?
