### ISSUE TITLE
gzip support ?

### ISSUE THREAD

**Issue by LBailly** [MikaAK/s3-plugin-webpack#13]
Would be cool to add gzip version of JS and CSS files during the process to offer CloudFront compression for free [CloudFront distribution](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#CompressedS3)

**Comment by MikaAK** [comment]
G-zip can be added with [Compression Plugin](https://github.com/webpack/compression-webpack-plugin) from webpack.
