### ISSUE TITLE
[FeatureRequest] add CloudFront support

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [MikaAK/s3-plugin-webpack#134]
Please add AWS CloudFront support.

Motivation:

1) AWS S3 is slow and for users assets (like avatars, uploaded video e.t.c.)
2) AWS CloudFront is fast and for site UI assets, like icons and styles.

webpack should not and cannot handle users assets, but webpack just needs to process site UI assets, which CloudFront  is for

**Comment by MikaAK** [comment]
AWS cloudfront is fully supported, you can do  cache invalidations already and S3 is just the storage while cloudfront is the CDN!
