### ISSUE TITLE
ERR_INVALID_ARG_TYPE (undefined) after upgrade to Webpack 5

### ISSUE THREAD

**Issue by samageloff** [MikaAK/s3-plugin-webpack#135]
**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood this plugin's README
- [x] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

Thank you for adhering to this process! This ensures that I can pay attention to issues that are relevant and answer questions faster.

# Issue Details

If filing a bug report, please include **a list of steps** that describe how to
reproduce the bug you are experiencing. Include your config being passed to the `S3Plugin`.

**Operating system**: `macOS Catalina 10.15.5`
**Node version**: `10.16.0`
**s3-plugin-webpack**: `1.0.3`
**webpack**: `5.0.0-beta.20`

**S3Plugin config**:
```
new S3Plugin({
  exclude: /.*\.html$/,
  include: /.*\.(css|js|gif|svg|eot|woff2|woff|ttf)/,
  s3Options: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    region: 'us-east-1',
  },
  s3UploadOptions: {
    Bucket: process.env.S3_ASSETS_BUCKET,
  },
}),
```

**Steps to reproduce**

1) Upgrade Webpack from `4.43.0` to `5.0.0-beta.20`
2) Run `webpack --config webpack.prod.js` (in this case)

I receive the following error:

```
98% after emitting webpack-s3-plugin
***** UPLOAD FILE ***** 687a4990ea22bb1a49d469a5d9319790.woff2 undefined
98% after emittingTypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.open (fs.js:408:3)
    at ReadStream.open (internal/fs/streams.js:110:12)
    at new ReadStream (internal/fs/streams.js:99:10)
    at Object.createReadStream (fs.js:1732:10)
    at t.exports.uploadFile (.../node_modules/webpack-s3-plugin/dist/s3_plugin.js:134:131)
    at t.map.t (.../node_modules/webpack-s3-plugin/dist/s3_plugin.js:123:103)
    at Array.map (<anonymous>)
    at transformBasePath.then (.../node_modules/webpack-s3-plugin/dist/s3_plugin.js:123:89)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

> While debugging, I added the ***** UPLOAD FILE ***** `console.log` to this method: 
https://github.com/MikaAK/s3-plugin-webpack/blob/master/src/s3_plugin.js#L288 

When on webpack 4.43.0, the second parameter returns the full file path, and not `undefined` as it does now. 

To the best of my knowledge, we're following documentation as specified. I've looked through any issues that might be related, and none seem to be directly related. 

> Note: the app is not using create-react-app.

Any help is appreciated. 

Best, 
Sam

**Comment by samageloff** [comment]
Could be directly related to this? https://github.com/MikaAK/s3-plugin-webpack/issues/119#issuecomment-514384061

**Comment by MikaAK** [comment]
Hey @samageloff this is indeed the case!! We'll need to make the fix for Webpack 5, I'll have some free time probably next weekend, but in the meantime PR's would be much welcome!

**Comment by samageloff** [comment]
@MikaAK revisiting this one a bit, to see if I can assist in any refactor work. Interestingly, I am unable to replicate the issue above, after upgrading to the latest Webpack beta (25). Having said that, there are some configuration items to address, as the tests fail.

**Comment by OllieJennings** [comment]
@MikaAK any update on this, l just tried upgrading to Webpack 5, and i've hit the same error

**Comment by MikaAK** [comment]
@OllieJennings not really, I honestly don't write JS apps anymore and am mainly in Elixir, so it's hard to find the time to fix this, PR's are appreciated, but I may be able to tackle this for the new year

**Comment by OllieJennings** [comment]
@MikaAK np, ill look into potentially doing a PR for this

**Comment by MikaAK** [comment]
1.2.0-rc.0 has been release @OllieJennings, let me know how it goes and I'll release a full version!

**Comment by OllieJennings** [comment]
@MikaAK will do, going to use it in a prod release today, will keep you posted

**Comment by OllieJennings** [comment]
@MikaAK can confirm this works perfectly now, our production apps work just find with the RC

**Comment by MikaAK** [comment]
Awesome, I'll leave it an RC for the next month for people to try out and if all is good I'll release fully! 

Thanks again for your work @OllieJennings 🙏🏽

**Comment by gingerchris** [comment]
We just installed this RC as part of an upgrade to Webpack 5 and looks to be working well.  Thanks all for your work!

**Comment by mrudult** [comment]
I'm still getting this error with the following versions and node version v16.10.0:

```
"webpack": "^5.64.0",
"webpack-cli": "^4.1.0",
"webpack-dev-server": "^3.1.4",
"webpack-s3-plugin": "^1.0.2"
```

```
[webpack-cli] TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at new ReadStream (node:internal/fs/streams:171:5)
    at Object.createReadStream (node:fs:2869:10)
    at t.exports.uploadFile (/Volumes/Workplace-SSD/Projects/Giftcard/giftcard-widget-zoid/node_modules/webpack-s3-plugin/dist/s3_plugin.js:1:6227)
    at /Volumes/Workplace-SSD/Projects/Giftcard/giftcard-widget-zoid/node_modules/webpack-s3-plugin/dist/s3_plugin.js:1:5869
    at Array.map (<anonymous>)
    at /Volumes/Workplace-SSD/Projects/Giftcard/giftcard-widget-zoid/node_modules/webpack-s3-plugin/dist/s3_plugin.js:1:5857
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
