### ISSUE TITLE
TypeError: Cannot read property 'getAllFilesRecursive' of undefined

### ISSUE THREAD

**Issue by Dids** [MikaAK/s3-plugin-webpack#15]
Getting the following error using the latest version:

```
95% emit/Users/Dids/Documents/React/<snip>/node_modules/webpack-s3-plugin/dist/s3_plugin.js:190
                _this2.getAllFilesRecursive(file).then(function (res) {
                      ^

TypeError: Cannot read property 'getAllFilesRecursive' of undefined
    at /Users/Dids/Documents/React/<snip>/node_modules/webpack-s3-plugin/dist/s3_plugin.js:190:23
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by Dids** [comment]
Tried with v0.6.0, but it's showing the same error.

**Comment by ekosz** [comment]
I'm getting the same problem. Version: 0.6.1 and Webpack 1.12.9

**Comment by karlhorky** [comment]
Same issue here with `0.6.1` and Webpack `1.12.9`.

Any update on when this will be fixed? Is there a workaround I can use in the meantime?

**Comment by ekosz** [comment]
@karlhorky I downgraded back to `0.5.1`

**Comment by karlhorky** [comment]
Yeah I tried that as well, but unfortunately I need the recursive functionality from #8 :stuck_out_tongue:

**Comment by MikaAK** [comment]
Ok, I think I finally fixed this one. Sorry for the delay. `0.6.2` has the changes. I also changed the recursive test so that I got this error!

**Comment by karlhorky** [comment]
Works great, thanks for the quick fix @MikaAK!
