### ISSUE TITLE
Windows Directories Translates to \ File Name Character in S3

### ISSUE THREAD

**Issue by ohadwkn** [MikaAK/s3-plugin-webpack#18]
I'll gladly add more information if the bug is not reproducible

**Comment by lostjimmy** [comment]
I made some of the initial fixes for windows support in pull request 14. I've been using it successfully since then. Can you share you webpack config and an example of a filename you're seeing in S3?

**Comment by ohadwkn** [comment]
Filename:
App\AdWingman\UI Test\lib\WingmanDriver.js

Config:
{
    devtool: 'eval-source-map',
    entry: {
      ii: [
        './App/AdWingman/ii/main.js'
      ]
    },
    output: {
      filename: '[name].js',
      path: path.join(__dirname, 'App/AdWingman/dist'),
      publicPath: '/App/AdWingman/'
    },
    plugins: [
      new S3Plugin({
        s3Options: {
          accessKeyId: 'xxxxxxx',
          secretAccessKey: 'xxxxxx',
          region: 'us-west-2'
        },
        s3UploadOptions: {
          Bucket: 'xxxxxxx'
        },
        directory: path.join(__dirname),
        basePath: 'testing',
        cdnizerOptions: {
          defaultCDNBase: 'no'
        }
      })
    ],
    module: {
      loaders: [
        {
          test: /\.jsx?$/,
          include: path.join(__dirname, 'App/AdWingman/ii'),
          loader: 'react-hot!babel'
        },
        {
          test: /\.scss$/,
          include: path.join(__dirname, 'App/AdWingman/ii'),
          loader: 'style!css!sass'
        }
      ]
    }
  }

Thanks

**Comment by MikaAK** [comment]
I'm guessing it's because of your publicPath having a trailing slash. As a workaround you can try removing that and I wil work on ensuring that no file gets uploaded with a double slash

**Comment by ohadwkn** [comment]
Unfortunately it didn't solve it.
I even change the public path to
```
      publicPath: path.join(__dirname, 'App/AdWingman')
```
But it still uploading a flattened version of the build with the directories structure in the file name.

**Comment by lostjimmy** [comment]
This looks like the correct behavior.

Chances are your configuration is not correct. You've set the `directory` option of the plugin to `__dirname`. This will cause the plugin to recursively grab all files in your project's directory. That directory is then removed from the filename before being uploaded. So, for instance, if your project's directory is `C:\dev\wingman`, your example file is at `C:\dev\wingman\App\AdWingman\UI Test\lib\WingmanDriver.js`, and the directory is being removed, leaving you with `App\AdWingman\UI Test\lib\WingmanDriver.js`, which is what you're seeing.

You should be setting directory to the output directory, or you should not set it at all. Note that if you don't set the directory, then the plugin will prepend `publicPath` as part of the file name.

**Comment by ohadwkn** [comment]
I see.
So the plugin is uploading only a flattened directory?

**Comment by MikaAK** [comment]
@ohadwkn "the plugin to recursively grab all files in your project's directory"

**Comment by MikaAK** [comment]
I think this another issue altogether actualy. Reading the [docs](https://webpack.github.io/docs/configuration.html#output-publicpath) `publicPath` is only used when serving the files from the browser and should probably not be used the way it is currently. I will remove the usage of `publicPath`.

**Comment by MikaAK** [comment]
@ohadwkn Fix is up let me know if it works

**Comment by ohadwkn** [comment]
It seems correct to use the path and not the publicPath in the context of the S3 uploader.
But, the change did not affected my issue. 
I updated to webpack-s3-plugin@0.6.4 and tried to upload a directory with directory in it and it flattens the directory.
I didn't understand, is it by design?

**Comment by MikaAK** [comment]
@ohadwkn No that is not by design. By default, it should create the folders for you and in the tests it reflects this. Your the only case that this is happening to so far so it could be your configuration. I will need more time to look into this

**Comment by ohadwkn** [comment]
@MikaAK 
I forked and added a string manipulation in filterPathFromFiles function (now filterAndTranslatePathFromFiles), from the PATH_SEP to S3 path seperator (/), this made the plugin create directories in the s3 bucket.
I created a pull request if you want to merge.

**Comment by MikaAK** [comment]
Nice solve. Weird the tests didn't catch this nor did it happen with anyone else though!

**Comment by ohadwkn** [comment]
Maybe everyone ported from windows.... :)
