### ISSUE TITLE
Files other than css/js

### ISSUE THREAD

**Issue by alex88** [MikaAK/s3-plugin-webpack#22]
My webpack build actually produces images, stylesheets, javascripts and html, however with this config:

```
new S3Plugin({
        include: /.*/,
        s3Options: {
          accessKeyId: process.env.AWS_ACCESS_KEY_ID,
          secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
          region: process.env.REGION
        },
        s3UploadOptions: {
          Bucket: process.env.BUCKET,
          ACL: 'public-read'
        }
      })
```

it uploads only css and js files, is there something wrong with what I'm doing?

**Comment by MikaAK** [comment]
You can use the `directory` option to upload your full directory of everything. Some strats I've seen before use the [copy-webpack-plugin](https://www.npmjs.com/package/copy-webpack-plugin) to move all their build files into a single folder before uploading it via the `directory` option of the s3Plugin.

**Comment by alex88** [comment]
Because my webpack configuration builds everything in the build folder, so I have

```
prj/dist/index.html
prj/dist/assets/javascripts.js
...
```

and also the html file is the output of webpack plugins. From the readme it's not clear what's actually uploaded and what not, my include option should include everything right?

**Comment by alex88** [comment]
Since the directory option `defaults to webpack output directory` I assume that all the `dist/` folder is uploaded

**Comment by MikaAK** [comment]
@alex88 Changed the README with the proper description `if not supplied will upload js/css from compilation`. Which means it will only upload files from your compilation that are js/css. If you supply the `directory` option it will take all the files in that directory and upload them, not just the js/css.

**Comment by alex88** [comment]
Oh now it's much more clear, sorry for bothering! It works! ;)

**Comment by jimmyn** [comment]
@MikaAK I have the same problem. I have a `dist` folder with all files I want to upload.

**My plugin config**

```
webpackConfig.plugins.push(
      new S3Plugin({
        directory: path.join(__dirname, config.destination),
        s3Options: {
          accessKeyId: process.env.AWS_ACCESS_KEY_ID,
          secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
          region: process.env.REGION
        },
        s3UploadOptions: {
          Bucket: 'landings.moonmail.io'
        }
      })
    );
```

**This is a list of my files**
<img width="422" alt="screenshot 2016-10-17 12 47 51" src="https://cloud.githubusercontent.com/assets/5391775/19433092/fce56a9c-9467-11e6-8fe8-611e166dd078.png">

**This is what gets uploaded to S3**
<img width="560" alt="screenshot 2016-10-17 12 48 12" src="https://cloud.githubusercontent.com/assets/5391775/19433093/fce95a44-9467-11e6-83c6-3675a4e304cb.png">

I've tried to `include` and `exclude` and anything I can think of and somehow it still skips `.html` files. Any ideas what I'm doing wrong?
