### ISSUE TITLE
CDNizer + image requires + Uglify

### ISSUE THREAD

**Issue by bgannonPL** [MikaAK/s3-plugin-webpack#25]
Hi, I'm having a hard time getting CDNizer setup in a way that makes sense. Since this is webpack, a lot of my images (all of them, probably) are going to be translated to `require`s by webpack, so they won't match the default matchers in CDNizer (which looks for CSS urls, img tags, etc.). That in itself is no big deal -- I started setting up a custom matcher, but then ran into an issue. This plugin is running CDNizer on the 'after-emit' plugin point, and the UglifyJS plugin does its work on 'optimize-chunk-assets' -- so CDNizer is trying to do find/replace on source that's already been uglified (assuming you're using the Uglify plugin). So if I were to write a custom matcher for the images I'm requiring, I'd have to write a pattern to match what Uglify spits out -- and that seems fragile, I'm not confident that Uglify is always going to give me `e.exports=n.p`, for example. 

Since image `require`s and the Uglify plugin are in pretty widespread use this seems like a significant issue. Wouldn't it be preferable for CDNizer to work on module source at some point before any post-processing occurs? Or is there something I'm missing -- can CDNizer somehow be used with image `require`s and Uglify without issues?

**Comment by MikaAK** [comment]
I never actually meant to cdnize image URLs with this, my use case was solely for injecting scripts into the html files. This will need more work before this works with images I'm guessing.

**Comment by MikaAK** [comment]
@bgannonPL Have you tried using https://github.com/webpack/file-loader in production? This looks like it does what you wan
t!

**Comment by bgannonPL** [comment]
@MikaAK I didn't realize that publicPath could be set to a URL (I took 'path' at face value). So yeah, I think if your publicPath is the CDN url then file-loader will work. Realized this after making a custom loader, though :P Thanks-

**Comment by MikaAK** [comment]
No problem! I'm glad this got brought up because I've never done this before. Would you mind explaining how you achieved what you got @bgannonPL? I want to put it in the readme because I think that it would be good info to have!

**Comment by bgannonPL** [comment]
Sure -- the `file-loader` (or the `url-loader`, which proxies to the `file-loader`) returns a url for the image you're loading that is based on webpack's `output.publicPath` config, basically concatenating them together. So if you set your publicPath to `http://my.cdn.com/`, the image URLs in your bundle will be relative to that url, e.g.` url('~some_image.png')` becomes `url(http://my.cdn.com/some_image.png)`. You would still have to handle the actual s3 upload independently, e.g. with this plugin.

The only potential snare (besides the fact that you might not expect 'publicPath' to take a URL as a value) is if that publicPath is used for other stuff besides just images; if you were putting some resources on your CDN but not all of them, you might have to wire up another solution.

**Comment by MikaAK** [comment]
Thanks! Will update the readme with a summary :smile:

**Comment by MikaAK** [comment]
@bgannonPL I was wondering if I could grab your input, I'm thinking of making publicPath be the default `defaultCDNBase` if none is provided. What do you think about this?

**Comment by bgannonPL** [comment]
Personally I think it's better to throw an error if no CDN value is provided. Using publicPath isn't necessarily intuitive, and the two shouldn't necessarily be linked. In reference to my comment above, I'm now at a point w/my project where I can't use a CDN for my publicPath (because some resources need to be served relative to the site URL and not from a CDN), and am back to using a custom loader to modify resource URLs as files are loaded.

**Comment by MikaAK** [comment]
Hmm but then how would you work with file-loader? file-loader also uses public path to be able to set the url so if you upload your files then you need to set publicPath to your cdn url or your files will not load!

**Comment by bgannonPL** [comment]
My loader replaces file-loader (which is very simple, so easy to replace) -- there's no sense in trying to play nicely with it given that the needed functionality is different.

**Comment by johnyoonh** [comment]
@bgannonPL would you be able to share your custom loader? I am also facing a similar issue with some resources served relative to the site URL.
