### ISSUE TITLE
No progress indicator?

### ISSUE THREAD

**Issue by msokk** [MikaAK/s3-plugin-webpack#29]
What happened to progress bar? :)

**Comment by MikaAK** [comment]
I disabled it temporarily till I could fix it, for some reason the tracking was very inaccurate. I'll keep this open as a reminder. I've been really busy recently and haven't had a chance to update this in a while. I've  got a branch going with a few fixes and some additions so I'll try to fix this by that release aswell. [Related LOC](https://github.com/MikaAK/s3-plugin-webpack/blob/master/src/s3_plugin.js#L281-L298)
