### ISSUE TITLE
js isn't being uploaded

### ISSUE THREAD

**Issue by MikaAK** [MikaAK/s3-plugin-webpack#34]
It's uploading css but not js. Please downgrade to `0.6.7` momentarily while it's being fixed. Not sure how tests passed this!

**Comment by jdrew1303** [comment]
👍 I was wondering what was happening. Thanks for posting here, most lib devs dont bother. Also thanks for the great lib! 😃

Also it seems to be any file except the css and index files:

![image](https://cloud.githubusercontent.com/assets/2535432/14726817/f824a928-081c-11e6-9d69-ce93a78b07aa.png)

![image](https://cloud.githubusercontent.com/assets/2535432/14726825/06637578-081d-11e6-97b8-692fba570cf7.png)

Hope this helps.

**Comment by MikaAK** [comment]
Fixed in `0.7.2`. Anyone on `0.7.1` please upgrade!!
