### ISSUE TITLE
Ability to set s3 metadata to specific file type

### ISSUE THREAD

**Issue by AOlefirenko** [MikaAK/s3-plugin-webpack#35]
Hi. Here is my case:
I'm using s3 for hosting multipage application. Since s3 doesn't provide url rewriting feature I use the follow workaround: upload html files (app, admin) without .html extension and add metadata ContentType: text/html
Also I'm going to add cache control attribute for all files excluding html.

Is there ability to set metadata as I described above in the current version? If not, how can i implement it better? Do you plan to add this feature?

**Comment by MikaAK** [comment]
With odd setups comes odd solutions 😂  `s3UploadOptions` can be used to set ContentType it's in the readme. You may need to use two instances of the uploader one for your html and one for the rest of your app.

**Comment by AOlefirenko** [comment]
Good option, thank you!:)
