### ISSUE TITLE
Alpine Linux - doesn't run

### ISSUE THREAD

**Issue by andreimc** [MikaAK/s3-plugin-webpack#37]
Hey,

Great work on this. I am using this in a project inside a docker container on top of alpine linux, and this plugin doesn't run as part of my build.

Any ideas why ?

Regards

**Comment by MikaAK** [comment]
Sorry, I cannot assist with this. A) You provided absolutely no info asides an OS. B) Issues are for real issues that are from my library ***only***. This sounds like an environment issue.
