### ISSUE TITLE
Uploaded items with basePath get prepended with /

### ISSUE THREAD

**Issue by JulioC** [MikaAK/s3-plugin-webpack#39]
**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood this plugin's README
- [x] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

Thank you for adhering to this process! This ensures that I can pay attention to issues that are relevant and answer questions faster.

# Issue Details

Node: v6.0.0 32bits (Windows 10)
s3-plugin-webpack: 0.7.3

When using the plugin with the options `basePath` set, the files get correctly uploaded, but all the files in root directory have a path separator prepended to it's key.

Example:

```javascript
new S3Plugin({
      // normal upload options
      basePath: 'stage',
})
```

This will be uploaded as:

```
Bucket
└──stage
  ├──\index.html
  ├──\styles.css
  ├──\images
  │  └──logo.png
  └──\scripts
     ├──main.js
     └──admin.js
```

I was able to fix the issue bypassing [the call to transformBasePath](https://github.com/MikaAK/s3-plugin-webpack/blob/master/src/s3_plugin.js#L254), but I'm not sure about the side effects of that...

**Comment by MikaAK** [comment]
Looks like an issue with [this line](https://github.com/MikaAK/s3-plugin-webpack/blob/master/src/s3_plugin.js#L219) I'll remove it and test when I'm home 👍

**Comment by JulioC** [comment]
I can confirm removing that call to `addSeperatorToPath` is enough to solve it.
