### ISSUE TITLE
Europe servers

### ISSUE THREAD

**Issue by westn** [MikaAK/s3-plugin-webpack#4]
Seems like there is an issue when uploading to servers in Europe... probably related to this: http://www.sitefinity.com/developer-network/forums/set-up-installation/amazon-s3---must-be-addressed-using-the-specified-endpoint

```
ERROR in S3Plugin: PermanentRedirect: The bucket you are attempting to access mu
st be addressed using the specified endpoint. Please send all future requests to
 this endpoint.
´´´

**Comment by MikaAK** [comment]
Did you set `region` under `s3Options`. You could also try setting `endpoint`

**Comment by westn** [comment]
It uploaded files when I set region, though now I get the full path-names as file-names, and it doesn't seem to upload all my files.

I get file-names like ```c:\something\test.js``` where I should get ```test.js```

**Comment by MikaAK** [comment]
This is a very weird bug, do you have a way I can reproduce this? Something you can try is setting `basePath`

**Comment by MikaAK** [comment]
@westn Checking back on this issue, is this still a problem?
