### ISSUE TITLE
Errors do not make builds fail

### ISSUE THREAD

**Issue by joshfriend** [MikaAK/s3-plugin-webpack#40]
For example: if the bucket requested does not exist, the error is logged to the console, but the build does not fail as it should and returns a success (exit code `0`):

```
ERROR in S3Plugin: NoSuchBucket: The specified bucket does not exist
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
Uploading [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100% 0.0s
```

I also see that the output is out of order from what I expect, with upload progress text appearing in seemingly random spots in the log.

Environment:
- Node v6.2.0
- s3_plugin_webpack v1.0.3
- OSX 10.11.5

Example config:

``` js
const webpackMerge = require('webpack-merge');
const commonConfig = require('./webpack.prod.js');
const S3Plugin = require('webpack-s3-plugin');

module.exports = webpackMerge(commonConfig, {
  plugins: [
    new S3Plugin({
      exclude: /^.*\.(map|map\.gz)$/,
      s3Options: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
        region: 'us-west-2'
      },
      s3UploadOptions: {
        Bucket: 'something-that-doesnt-exist'
      },
      cloudfrontInvalidateOptions: {
        DistributionId: process.env.CLOUDFRONT_DISTRIBUTION_ID,
        Items: ['/*']
      }
    })
  ]
});
```

**Comment by mdreizin** [comment]
@MikaAK Any plans to fix it?

**Comment by MikaAK** [comment]
Yes but I'm very busy recently. PR's are welcome!

**Comment by flipxfx** [comment]
+1 this is needed to work with CI

**Comment by thescientist13** [comment]
I get something similar as well
```
19:47:07 
19:47:07 ERROR in S3Plugin: RequestTimeTooSkewed: The difference between the request time and the current time is too large.
19:47:07 Child html-webpack-plugin for "index.html":
```

@MikaAK 
I would be up for taking a look, presumably this is the line in question to update?
https://github.com/MikaAK/s3-plugin-webpack/blob/master/src/s3_plugin.js#L25

For making the build fail, would it be as simple as calling `process.exit()`?

**Comment by MikaAK** [comment]
@thescientist13  it's actually webpack responsibility to quit on error, we shouldn't be process.exit manually since people can choose to exit or not with the --bail option

**Comment by thescientist13** [comment]
I see, thanks @MikaAK .

I double checked my npm script and it is using `--bail`
```
"release": "export NODE_ENV=production && rimraf ./build && webpack --config ./webpack.config.release.js --progress --profile --bail"
```

This webpack config uses `webpack-merge` on a config (_webpack.config.prod.js_) that itself uses `webpack-merge` on a config (_webpack.config.common.js), so it's too much webpackception?  😆

**Comment by moust** [comment]
Same problem with AWS connection failure, it do not make fail the build.
