### ISSUE TITLE
SigV4 error issue 

### ISSUE THREAD

**Issue by root-shkim** [MikaAK/s3-plugin-webpack#43]
[SigV4 Policy](http://docs.aws.amazon.com/ko_kr/AmazonS3/latest/API/bucket-policy-s3-sigv4-conditions.html)

My bucket is in ap-northeast-2 which has to set SigV4.
When I build, it cannot upload to S3 with message 

`ERROR in S3Plugin: Error: Non-file stream objects are not supported with SigV4 in AWS.S3`

Do you have plan to add an 'option' for SigV4?

My environment is below:

Node v4.2.3
webpack-s3-plugin@0.8.0 
OSX 10.10.5

Example config

```
module.exports = {
    new S3Plugin({
      // s3Options are required
      s3Options: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
        region: 'ap-northeast-2'
      },
      s3UploadOptions: {
        Bucket: 'my'
      }
    })
  ]
};
```

**Comment by MikaAK** [comment]
No plans currently to add this at this time but I can look into it later. This isn't really a bug so much as a feature request right? I'll add it to the todo list but I'm really busy as of late so if you really need it asap I would recommend creating a PR with the provided functionality!

**Comment by root-shkim** [comment]
Thank you for your quick comment!
You are right, this is not a bug. :)
I'll try to PR but since I'm a beginner of Webpack and Javascript, it takes a long time.

**Comment by MikaAK** [comment]
Thanks! Feel free to [email](mailto:mika@kalathil.me) me with any questions along the way if you need!

**Comment by fabianfett** [comment]
This seems to be related to an outdated 'aws-sdk' version in 's3':
https://github.com/andrewrk/node-s3-client/issues/69

This seems to be fixed, 
https://github.com/andrewrk/node-s3-client/pull/142

Sadly they didn't release a new 's3' version yet. I just updated the package.json to use the github master, which works like a charm. @MikaAK: What do you think, does it make sense, to link against the github version for the time being?

**Comment by MikaAK** [comment]
No it never makes sense to link directly to github in a library in my opinion.  Your to vulnerable to breaking changes and have no idea when they may push something that breaks.  We will have to wait on a release,  alternatively we can just use the sdk directly and drop the dependency on s3

**Comment by dilame** [comment]
I have this error, but it is problem for me, because i dont know what i am doing wrong. 
```
module.exports.plugins.push(
    new S3Plugin({
      // s3Options are required
      include: /.*\.(js)/,
      s3Options: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
        region: "eu-central-1",
      },
      s3UploadOptions: {
        Bucket: 'smmtool-static'
      }
    })
  )
```

**Comment by MikaAK** [comment]
https://github.com/andrewrk/node-s3-client/issues/139 will switch off when I have time

**Comment by dilame** [comment]
Sorry, but i still dont get how to make it work now?

**Comment by denyago** [comment]
I'm sorry, but this great plugin is not usable for me because of this issue.

Is there any workaround for it?

I've added

```
  "devDependencies": {
// ...
    "webpack-s3-plugin": "^0.9.0",
    "s3": "git://github.com/andrewrk/node-s3-client.git#0ed018699843a2d3cc1cb37399ead1f76a72576d"
  }
```

and 

```js
    new S3Plugin({
      include: /.*\.css$/,
      s3Options: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY
        region: 'eu-central-1'
      },
      s3UploadOptions: {
        Bucket: 'my-bucket'
      },
      basePath: 'my-stage'
    })
```

And I still get

```
ERROR in S3Plugin: Error: Non-file stream objects are not supported with SigV4 in AWS.S3
```

**Comment by fabianfett** [comment]
As long as this problem exists you can use my hacky fork.
https://github.com/fabianfett/s3-plugin-webpack just 
```
npm install git+https://github.com/fabianfett/s3-plugin-webpack.git
```

Hope that helps.

**Comment by denyago** [comment]
Thanks, @fabianfett but I have "Access denied" error now. 

Just ignore me, I'll try good old Ruby and https://github.com/hooktstudios/capistrano-s3

**Comment by dilame** [comment]
@denyago it seems like problem only with 'eu-central-1' region. Frankfurt. Try to use Ireland region. It solved this problem for me.

**Comment by AlexDWu** [comment]
Add `signatureVersion: 'v3'` to `s3options`

**Comment by dennisoverbeeke** [comment]
@MikaAK I see you re-opened this issue. Are you planning to add Signature V4? So we can use newer S3 region expecting this v4 signature?

**Comment by MikaAK** [comment]
Yes,  currently I have to much to do and I'm on vacation so I would expect it anytime within the next month unless someone submits a pr

**Comment by glorp47** [comment]
I've been having the same errors while trying to use this plugin ... the fix from @fabianfett seemed to work

**Comment by sercaninaler** [comment]
+1

**Comment by Mil0dV** [comment]
Not sure why there is no PR yet, it's literally one line of code: https://github.com/fabianfett/s3-plugin-webpack/commit/d92893d40ce433697caaf816df4cca813a8191e7 (I'd create one myself, but I really need to ship the MVP for my startup this weekend..)

Btw, possible addition to the readme: using an AWS credentials file is possible like this:
```
    new S3Plugin({
      // Exclude uploading of html
      exclude: /.*\.html$/,
      // s3Options are required
      s3Options: {
        region: 'eu-central-1'
      },
      s3UploadOptions: {
        Bucket: 'bucket-static'
      }
    })

**Comment by MikaAK** [comment]
@Mil0dV you typically don't want to point to master since it's unstable and not guaranteed to be the same. That being said it's not really an active repo so maybe this is a good idea considering it doesn't seem to be actively maintained. Perhaps it's a good quick fix while it's being written out.

**Comment by Mil0dV** [comment]
@MikaAK alternatively you could point it at a specific commit I'd say - I can't really figure out when they fixed this, but since the repo seems quite dead you could just point at the latest at this moment.

**Comment by sercaninaler** [comment]
Since there is not a hotfix, You can use this repo as well:
"webpack-s3-plugin": "git+https://github.com/eyupci/s3-plugin-webpack.git#master"

**Comment by a-eid** [comment]
@AlexDWu when I add that I get an access denied 

`ERROR in S3Plugin: AccessDenied: Access Denied`

**Comment by a-eid** [comment]
@MikaAK could you explain what are ` Non-file stream objects ` ?

**Comment by YukSeungChan** [comment]
+1

**Comment by esperancaJS** [comment]
- with `signatureVersion: 'v3'`:

   ```js
      s3Options: {
        accessKeyId: '...',
        secretAccessKey: '...',
        signatureVersion: 'v3'
      },
   ```

  I get:

  ![image](https://user-images.githubusercontent.com/1115163/35931434-88047b12-0c2c-11e8-892b-98704a0ddf94.png)

- with `signatureVersion: 'v4'`:

   ```js
      s3Options: {
        accessKeyId: '...',
        secretAccessKey: '...',
        signatureVersion: 'v4'
      },
   ```

  I get:

   ![image](https://user-images.githubusercontent.com/1115163/35931633-141ab2f6-0c2d-11e8-8ea8-96d60f905829.png)

**Comment by cc5tudio** [comment]
I was able to fix this by pointing my package.json to the following branch:

"webpack-s3-plugin": "https://github.com/johnf/s3-plugin-webpack#soaa"
