### ISSUE TITLE
cdnizerCss option is not working

### ISSUE THREAD

**Issue by vladiacob** [MikaAK/s3-plugin-webpack#50]
# Complete the following or your issue will be deleted (delete me after)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [x] I have read and understood this plugin's README
- [x] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

Thank you for adhering to this process! This ensures that I can pay attention to issues that are relevant and answer questions faster.

# Issue Details
Hello, 
 
   I'm not able to use cdnizerCss option, is not working at all. Path for images and fonts remain exactly the same in my css file.

Thanks.

```
new S3Plugin({
			include: /.*\.(eot|svg|ttf|woff|woff2|otf)/,
			s3Options: {
				accessKeyId: process.env.AWS_ACCESS_KEY_ID,
				secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
				region: process.env.AWS_REGION
			},
			s3UploadOptions: {
				Bucket: 'my-bucket'
			},
			basePathTransform: addSha,
		    cdnizerCss: {
				test: /fonts/,
				cdnUrl: "http://test.com"
			},
			cdnizerOptions: {
		        defaultCDNBase: 'http://asdf.ca'
		      }
		}),
```

**Comment by MikaAK** [comment]
This made it into the readme by mistake.  Cdnizecss isn't available yet,  it's reccommend you use file loader for that for now.

**Comment by MikaAK** [comment]
Closing, use file loader

**Comment by thebigredgeek** [comment]
@MikaAK uhhh... any update on this?  I need to be able to change url references in CSS to point to CDN location... cdnizr has documentation for parsing URLs in CSS.  Is there a reason this isn't supported on this plugin?

**Comment by MikaAK** [comment]
There are other ways to change the url of your css file so doing it via this plugin isn't necessary

**Comment by elhesuu** [comment]
Should this option be removed until it's available? It might be confusing otherwise.

**Comment by thebigredgeek** [comment]
^ agreed

**Comment by MikaAK** [comment]
Will do sorry been outrageously busy and haven't had time to update but it's coming soon I promise!
