### ISSUE TITLE
Content-Type not being set correctly

### ISSUE THREAD

**Issue by swaroopsm** [MikaAK/s3-plugin-webpack#51]
I have set the `Content-Type` option as follows, but in my `S3` it is being set as: `application/x-www-form-urlencoded`

```
ContentType: (fileName) => {
          if (/\.js/.test(fileName)) {
            return 'application/javascript'
          }

          if (/\.css/.test(fileName)) {
            return 'text/css'
          }
}
```

Environment:
- Node v4.4.7
- s3-plugin-webpack v0.9.0
- OSX 10.11.6 

Is this an issue with the `s3` package itself?

**Comment by MikaAK** [comment]
options are piped right to s3,  are you using compression plugin by chance? Try console.log in the function and confirming the file is getting handled properly

**Comment by swaroopsm** [comment]
The `ContentType` is being set correctly before uploading to `s3`, i.e., in the `uploadFile` function of `s3` module. And I am not using `compression` plugin.

**Comment by MikaAK** [comment]
Have you tried not setting ContentType? I hardly ever do

**Comment by swaroopsm** [comment]
Yes I have tried without the `ContentType` option. Still no luck.

**Comment by MikaAK** [comment]
Can you provide a repo with a reproduction of this? I can't reproduce this in any way unfortunately

**Comment by jiverson** [comment]
Same and the interesting thing is some of the files are getting set correctly while others are not.

**Comment by MikaAK** [comment]
Which are not? S3 package automatically sets content type

**Comment by paolavness** [comment]
Is there is a solution for this?

I am experiencing this issue - I am using compression tho. My config is below. For gzipped files, ContentEncoding is simply not being set and ContentType is being set to 'application/octet-stream' 

```
        new CompressionPlugin({
            asset: "[path].gz[query]",
            algorithm: "gzip",
            test: /\.(js|css)$/,
            threshold: 10240,
            minRatio: 0.8,
            deleteOriginalAssets: true            
        }),

        new S3Plugin({
                s3Options: {
                    region: 'xxx'
                },

                s3UploadOptions: {
                    Bucket: 'xxx'
                },

                ContentEncoding(fileName) {
                if (/\.gz$/.test(fileName))
                    return 'application/gzip'   //have tried 'gzip' with no effect
                },

                ContentType(fileName) {
                if (/\.(js|js.gz)$/.test(fileName)) 
                    return 'application/javascript'
                else if (/\.(css|css.gz)$/.test(fileName))
                    return 'text/css'
                else
                    return 'text/plain'
                },
```
