### ISSUE TITLE
Delete previous builds

### ISSUE THREAD

**Issue by jimmyn** [MikaAK/s3-plugin-webpack#54]
Is there any way to delete previous files? I use hash in file names to invalidate only `index.html` but every time webpack generates a new hash value I got duplicated files in my S3 bucket. Is there any way to avoid that?

**Comment by MikaAK** [comment]
That's outside the scope of this plugin

**Comment by ianks** [comment]
@MikaAK I'm not sure why it would be outside the scope of this plugin? Can you elaborate? Other tools (i.e. s3_website) handle this use case. From a user's POV, this feature would save a ton of hassle.

**Comment by MikaAK** [comment]
This is more of an uploader but is turning into something more robust. Surprise and change is coming very soon just wait till then and maybe we can look back into it @ianks
