### ISSUE TITLE
Region always set to us-west-2 when using AWS best practices

### ISSUE THREAD

**Issue by atomaka** [MikaAK/s3-plugin-webpack#56]
- [X] I have read and understood this plugin's README
- [X] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [X] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [X] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [X] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [X] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**
# Issue Details

I don't think these are relevant, but to knock off your checklist super quick:

node version: v5.0.0
s3-plugin-webpack: `"webpack-s3-plugin": "^0.9.0"`
OS: MacOS 10.12.1 (16B2555)

The README outlines that this plugin supports AWS best practices of for credentials.  I am experiencing an issue with this that can be repeated with the following:

1) Create a set of credentials in AWS
2) Create an S3 bucket in the "Standard" (us-east-1) S3 region
3) Update your credentials file with

```
[default]
region = us-east-1
aws_access_key_id = YOUR_KEY_ID
aws_secret_access_key = YOUR_ACCESS_KEY
```

4) Configure S3 Plugin without `s3options`.

When doing this, I receive the following error:

```
ERROR in S3Plugin: PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

If I create a bucket in `us-west-2`, update my configuration to point at it and repeat the test, I receive no error message.

If I specify `s3options` with `us-east-1`, it works.

The problem is the result of 

```
s3Options: _.merge({}, DEFAULT_S3_OPTIONS, s3Options)
```

Since `s3Options` is empty when credentials are provided via AWS best practices, your defaults always make it into the client.

**Comment by MikaAK** [comment]
For sure this is a good idea. however, this would be a very breaking change for people reliant on it so I'll bundle it in with a bigger update.

**Comment by atomaka** [comment]
I understand this is a breaking change and that people may rely on current behavior.  However, I believe this should be marked a bug.  This is unexpected behavior for people who favor credentials file or environment settings.

In the meantime, would you be willing to accept a pull request noting this?

**Comment by MikaAK** [comment]
yeah for sure I can, if you fill a PR fixing this issue it would be even better 👍 that way I can just merge it in when I'm done with some upgrades

**Comment by atomaka** [comment]
@MikaAK The only way I can see this being fixed is complete removal of `DEFAULT_S3_OPTIONS`.  What are your thoughts?

**Comment by MikaAK** [comment]
Agreed just region needs to be removed
