### ISSUE TITLE
When using IAM instances, "Must provide accessKeyId, secretAccessKey" error is thrown 

### ISSUE THREAD

**Issue by mohsen1** [MikaAK/s3-plugin-webpack#59]
Upload works and I can see the files but webpack errors out with `Must provide accessKeyId, secretAccessKey`

**Comment by nwhite89** [comment]
+1 for this I'm having Lambda generate my files and having them automatically upload to S3 it would be awesome to use this plugin with it directly with my IAM Roles.

**Comment by MikaAK** [comment]
#60 fixes this

**Comment by mingchuno** [comment]
when can we have a new release for fixing this?

**Comment by MikaAK** [comment]
Fixed in rc.0 👍  just making sure all is good before a release

**Comment by mohsen1** [comment]
I just deprecated my fork. Thanks!
