### ISSUE TITLE
S3Plugin: AccessDenied: Access Denied Error

### ISSUE THREAD

**Issue by rohi** [MikaAK/s3-plugin-webpack#63]
# Complete the following or your issue will be deleted (delete me after)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [ x] I have read and understood this plugin's README
- [ x] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [x ] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x ] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x ] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x ] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

Thank you for adhering to this process! This ensures that I can pay attention to issues that are relevant and answer questions faster.

# Issue Details
Plugin reports an Access Denied error if the bucket has no Upload/Delete permission for "Everyone". No other permission settings seems to be working. 

Node version 4.5.0
s3-plugin-webpack version 0.9.2
OS version Windows 8.1
If filing a bug report, please include **a list of steps** that describe how to
reproduce the bug you are experiencing. Include your config being passed to the `S3Plugin`.

1. Create a new bucket.
2. Ensure that bucket it has no other permission other than "Me"
3. Create an IAM user with All permission on this new bucket.
4. Try uploading file using s3-plugin-webpack plugin and error should appear on console.

**Comment by paolavness** [comment]
Wondering how you resolved this. Experiencing the same issue here. Our deplyoment works fine from Mac but same deployment getting Access Denied on windows. Uploading with the CLI using same credentials is fine.
