### ISSUE TITLE
Feature Request: Add ability to add Content-Length header to content

### ISSUE THREAD

**Issue by stevewillard** [MikaAK/s3-plugin-webpack#64]
As part of Cloudfront, if you specify a Content-Length header, you can automatically compress (gzip) your content.
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

Any thoughts on how this could be achieved?

**Comment by MikaAK** [comment]
Not sure.  You can set content-length for s3 but for cloudfront I'm not sure how you would configure that.  Asides invalidating it, cloudfront is outside the scope of this project currently
