### ISSUE TITLE
basePathTransform not accepting string

### ISSUE THREAD

**Issue by adnanoner** [MikaAK/s3-plugin-webpack#65]
- [x] I have read and understood this plugin's README
- [x] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [x] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [x] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [x] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [x] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

# Issue Details
node v7.3.0, s3-plugin-webpack v0.9.2, Mac OS 10.12.2

First of all: thanks for writing this great plugin 👍 . Much appreciated :).

When entering a string in basePathTransform, it is not working since it's expecting a function.

```
var dateFormat = require('dateformat');
new S3Plugin({
    exclude: /.*\.scss$/,
    s3Options: {
        accessKeyId: '...',
        secretAccessKey: '...',
        region: '...'
    },
    s3UploadOptions: {
        Bucket: '...'
    },
    basePathTransform: dateFormat(new Date(), 'yyyy-mm-dd-HH-ss'),
});
```

When I rewrite the dateFormat part to a promise it works:

```
var timestamp = function() {
  return new Promise(function(resolve, reject) {
    resolve(dateFormat(new Date(), 'yyyy-dd-HH-mm-ss'));
  })
}
```

I was expecting that a string was okay since the documentation says:

`basePathTransform`: transform the base path to add a folder name. Can return a promise or a string

But perhaps I misunderstood :)

**Comment by MikaAK** [comment]
basePathTransform isn't for returning a string. Use basePath itself for returning a string. BasePathTransform accepts functions only of which you can return a string or promise
