### ISSUE TITLE
Document that s3-plugin-webpack uploads object with public-read ACL and overrides bucket policies

### ISSUE THREAD

**Issue by hsanjuan** [MikaAK/s3-plugin-webpack#71]
- [X] I have read and understood this plugin's README
- [ ] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [ ] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [ ] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [X] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [X] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

# Issue Details

Default options set public-read ACL on every uploaded object: https://github.com/MikaAK/s3-plugin-webpack/blob/master/src/helpers.js#L10.

Object ACLs override S3 bucket policies, unless they are explicitally "Deny" (see https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-auth-workflow-object-operation.html). It pretty much opens the bucket to the world regardless of the policy users have set and this is mentioned nowhere. AWS bucket policy examples (https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html provides "Allow" examples mostly, so this likely causes security holes in buckets using default policies from the docs.

**Comment by torinagrippa** [comment]
Wow, good catch. That saved me from a lot of backtracking down the road.

**Comment by MikaAK** [comment]
Documented in readme
