### ISSUE TITLE
cdnizerOptions.defaultCDNBasePath config not working when output.publicPath is defined

### ISSUE THREAD

**Issue by thescientist13** [MikaAK/s3-plugin-webpack#73]
# Complete the following or your issue will be deleted (delete me after)

**Please complete these steps and check these boxes (by putting an `x` inside
the brackets) _before_ filing your issue:**

- [X] I have read and understood this plugin's README
- [X] If filing a bug report, I have included my version of node and s3-plugin-webpack
- [X] If filing a bug report, I have included which OS (including specific OS
  version) I am using.
- [X] If filing a bug report, I have included a minimal test case that reproduces
  my issue.
- [X] **I understand this is an open-source project staffed by someone with a job and
  that any help I receive is done on free time. I know I am not entitled to anything and will be polite and courteous.**
- [X] **I understand my issue may be closed if it becomes obvious I didn't
  actually perform all of these steps or the issue is not with the library itself**

Thank you for adhering to this process! This ensures that I can pay attention to issues that are relevant and answer questions faster.

# Issue Details
I noticed an issue that when defining `output.publicPath` in a Webpack configuration, `cdnizerOptions.defaultCDNBasePath` will not be reflected in the generated _index.html_

### Environment
```bash
$ node -v
v6.9.1
```
- OS: Mac OSX 10.12.4
- Webpack S3 Plugin: ^1.0.0-rc.0

### Webpack Config
```javascript
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');
const webpack = require('webpack');
const S3Plugin = require('webpack-s3-plugin');

module.exports = {
  context: path.resolve(__dirname, 'src'),

  entry: {
    index: './index.js',
    vendor: './vendor.js'
  },

  output: {
    path: path.join(__dirname, '/dest/web/abc'),
    publicPath: '/abc',
    filename: '[name].[chunkhash].bundle.js',
    sourceMapFilename: '[name].[chunkhash].bundle.map'
  },

  module: {
    rules: [{
      test: /\.js$/,
      exclude: /node_modules/,
      use: [{
        loader: 'babel-loader',
        options: {
          presets: [
            ['es2015', { modules: false }]
          ]
        }
      }, {
        loader: 'eslint-loader',
        options: {
          failOnWarning: false,
          failOnError: true
        }
      }]
    }, {
      test: /\.html$/,
      exclude: path.join(__dirname, './src/index.html'),
      use: [{
        loader: 'html-loader'
      }]
    }, {
      test: /\.less$/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: ['css-loader', 'less-loader']
      })
    }, {
      test: /\.(jpg|png|gif)$/,
      use: [{
        loader: 'file-loader'
      }]
    }, {
      test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'url-loader?limit=10000&mimetype=application/font-woff'
    }, {
      test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'file-loader'
    }]
  },

  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: ['vendor']
    }),

    new ExtractTextPlugin('[name].[chunkhash].style.css'),

    new HtmlWebpackPlugin({
      template: './index.html',
      chunksSortMode: 'dependency'
    }),

    new S3Plugin({
      s3Options: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
        region: 'xxx'
      },
      s3UploadOptions: {
        Bucket: 'xxx'
      },
      cdnizerOptions: {
        defaultCDNBase: 'http://abc123.cloudfront.net'
      },
      cloudfrontInvalidateOptions: {
        DistributionId: 'xxx',
        Items: ['/index.html']
      }
    })
  ]

};
```

### Generated index.html
```html
<!DOCTYPE html>

<html lang="en">

  <head>
    <base href="/">

  <link href="/abc/index.61ccaa401863e6e0122e.style.css" rel="stylesheet"></head>

  <body ng-app="ne">

    <ne-bootstrap>Loading...</ne-bootstrap>

  <script type="text/javascript" src="/abc/vendor.a42ee6ffe37f88d1821d.bundle.js"></script><script type="text/javascript" src="/abc/index.61ccaa401863e6e0122e.bundle.js"></script></body>

</html>
```

### Expected
`/abc/` would be replaced with the value of `defaultCDNBasePath` 

**Note: if the value of `output.publicPath` is an empty string, the expected behavior is seen**

**Comment by thescientist13** [comment]
Note sure if this would be expected or not.  

I suppose one solution could be to just delete `publicPath` or set it to an empty string when doing a "production" deployment?  Testing that right now.

**Comment by MikaAK** [comment]
Yeah they overlap. Don't set public path if you're setting defaultCDNBase and vice versa

**Comment by thescientist13** [comment]
great, thanks for the quick reply!
