### ISSUE TITLE
Adjusting file names when uploading to S3

### ISSUE THREAD

**Issue by StasD** [MikaAK/s3-plugin-webpack#75]
Hi,
Is it possible to adjust file name when uploading to S3?
My current setup is this:
```
        new CompressionPlugin({
            asset: "[path]",  // "[path].gz[query]"
            algorithm: "gzip",
            test:  /\.(js|css|map)$/,
            // threshold: 10240,
            minRatio: 10  // 0.8
        }),

        new S3Plugin({
            s3Options: {
                accessKeyId: 'xxx',
                secretAccessKey: 'xxx',
                region: 'xxx'
            },
            s3UploadOptions: {
                Bucket: 'xxx',
                ContentEncoding(fileName) {
                    if (/\.(js|css|map)$/.test(fileName)) {
                        return 'gzip';
                    }
                }
            },
            cloudfrontInvalidateOptions: {
                DistributionId: 'xxx',
                Items: ["/*"]
            }
        }),
```
As you can see, the CompressionPlugin overwrites .js, .css and .map files with their compressed version. Ideally, I would like it to retain the original uncompressed files, but skip them when uploading to S3, and instead upload .js.gz as .js etc. Is this possible to do with your plugin?
Thanks!

**Comment by MikaAK** [comment]
Add `exclude: /.(js|css)\.gz/`

**Comment by StasD** [comment]
Hi Mika,
I think you didn't understand my question.
I will actually `exclude: /.(js|css|map)$/`, not `include:` them.
But then I need to upload compressed versions of those files to S3 removing the .gz extension, e.g. `app.js.gz` should become `app.js` after uploading to S3. Is this possible?

**Comment by MikaAK** [comment]
Try  `asset: "[file]"` instead in compression plugin to make compression plugin not add .gz

**Comment by StasD** [comment]
OK, thanks for clarification!
P.S.: `asset: "[path]"` already doesn't add .gz.

**Comment by MikaAK** [comment]
Awesome! I'll try and look into some renaming for file names
