### ISSUE TITLE
Adding option for AWS Credentials --profile

### ISSUE THREAD

**Issue by paolavness** [MikaAK/s3-plugin-webpack#77]
Hi there,
Loving how this app is simplifying our flow.

One enhancement I'd love to see - we run a slightly more involved set and deploy different stages differently, with different users having aws credentials for different stages... IE, we use aws credentials.

It would be awesome to have an option to define the aws credentials profile to use.

Warmly,
Paola

**Comment by d3viant0ne** [comment]
Should be simple enough given the SDK handles this by default.

**Comment by rawberg** [comment]
Managed to get this working by loading the aws-sdk and leveraging that to retrieve profile specific credentials.
```
if (process.env.NODE_ENV === 'production') {
    const AWS = require('aws-sdk');
    const credentials = new AWS.SharedIniFileCredentials({profile: 'profile_name'});

     new S3Plugin({
         s3Options: {
             accessKeyId: credentials.accessKeyId,
             secretAccessKey: credentials.secretAccessKey
         }
     })
}
```

**Comment by ericrav** [comment]
since all of `s3Options` is passed through, you can simplify this to:
```
s3Options: {
  credentials: new AWS.SharedIniFileCredentials({ profile: 'PROFILE' }),
}
```

**Comment by MikaAK** [comment]
Huh, TIL @ericrav thank you I'll add this to the readme and close this issue
