### ISSUE TITLE
Recursive support?

### ISSUE THREAD

**Issue by Dids** [MikaAK/s3-plugin-webpack#8]
I'm trying to upload the contents of an entire directory (public/ in my case), which contains subfolders for my css, js etc.

I'm getting the following error:
```js
95% emitfs.js:844          
  return binding.lstat(pathModule._makeLong(path));
                                  ^
Error: ENOENT: no such file or directory, lstat 'bootstrap.min.css'
```

**Comment by Dids** [comment]
If it helps, here's my webpack output configuration (might have something to do with the issue):
```js
var ROOT_PATH = path.resolve(__dirname);
var APP_PATH = path.resolve(ROOT_PATH, 'src/js/entry.js');
var BUILD_PATH = path.resolve(ROOT_PATH, 'public/js');

publicPath: "/js/",
path: BUILD_PATH,
filename: "bundle.js"
```

I tried removing publicPath and path and setting filename to "public/js/bundle.js", but that didn't have any effect on the S3 plugin.

Essentially, all my static files are sitting in public/ and webpack is compiling my bundle from src/* to public/js/bundle.js, so I'd need the S3 plugin to upload everything in public/* to S3.

From the error message, I can tell that it's clearly going into public/css/, since it can find bootstrap.min.css, but it doesn't seem to be able to construct a proper path to it.

**Comment by thefron** [comment]
+1. Same happens to me

**Comment by MikaAK** [comment]
Sorry I completely did the recursive directory upload wrong, I've rewritten that functionality so it works but I would like to have some tests in place before I release the next build. I should be able to get to it tomorrow or later today. Thanks for your patient

**Comment by MikaAK** [comment]
@thefron and @Dids I've added in recursive support for directories. `v0.6.1`

**Comment by Dids** [comment]
@MikaAK Thanks!
